version: '3.8'

services: 
  redis:
    image: redis/redis-stack:latest
    container_name: reelix-redis
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
    networks: 
      - redis_network

networks:
  redis_network: {}

volumes:
  redis_data: