version: '3.8'

services: 
  redis:
    image: redis/redis-stack:latest
    container_name: reelix-redis
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
    networks: 
      - app_network

  postgres:
    image: postgres:latest
    container_name: reelix-postgres
    environment:
      POSTGRES_USER: reelix
      POSTGRES_PASSWORD: reelixServerPassword
      POSTGRES_DB: reelix-database
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: reelix-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@reelix.com
      PGADMIN_DEFAULT_PASSWORD: reelixPassword
    ports:
      - "5050:80"
    networks:
      - app_network

networks:
  app_network: {}

volumes:
  redis_data:
  postgres_data: