version: '3.8'

services: 
  redis:
    image: redis/redis-stack:latest
    container_name: reelix-redis
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
    networks: 
      - app_network

  postgres:
    image: postgres:latest
    container_name: reelix-postgres
    environment:
      POSTGRES_USER: reelix
      POSTGRES_PASSWORD: reelixServerPassword
      POSTGRES_DB: reelix-database
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  adminer:
    image: adminer:latest
    container_name: reelix-adminer
    ports:
      - '8080:8080'
    networks:
      - app_network

networks:
  app_network: {}

volumes:
  redis_data:
  postgres_data: